import numpy as np
import matplotlib as mpl
mpl.use("Agg")
import matplotlib.pyplot as plt
import h5py as hdf
from rachelutils.hdfload import getvar

w11 = getvar('/nobackup/rstorer/convperts/revu/aug11-control/aug11-control-revu-026.h5','w')
w17 = getvar('/nobackup/rstorer/convperts/revu/aug17-control/aug17-control-revu-021.h5','w')
w23 = getvar('/nobackup/rstorer/convperts/revu/feb23-control/feb23-control-revu-016.h5','w')
q11 = getvar('/nobackup/rstorer/convperts/revu/aug11-control/aug11-control-revu-026.h5','total_cond')
q17 = getvar('/nobackup/rstorer/convperts/revu/aug17-control/aug17-control-revu-021.h5','total_cond')
q23 = getvar('/nobackup/rstorer/convperts/revu/feb23-control/feb23-control-revu-016.h5','total_cond')
z = getvar('/nobackup/rstorer/convperts/revu/feb23-control/feb23-control-revu-016.h5','z_coords')/1000.
x = np.arange(400)*.25
fig = plt.figure()
plt.subplot(3,2,1)
maxw11=np.max(w11,1)
plt.contourf(x,z,maxw11,cmap=plt.get_cmap('plasma'))#,levels = np.linspace(0,48,9))
plt.colorbar()
plt.xticks([])
plt.ylabel('Aug 11',rotation=0,labelpad=30,fontweight='bold')
plt.title('Max Updraft')
plt.ylim(0,20)
plt.subplot(3,2,2)
maxq11=np.max(q11,1)
maxq11[maxq11<0.001]=np.log(0)
plt.contourf(x,z,maxq11,cmap=plt.get_cmap('plasma'))#,levels = np.linspace(0,24,9))
plt.title('Max Condensate')
plt.colorbar()
plt.xticks([])
plt.yticks([])
plt.ylim(0,20)
plt.subplot(3,2,3)
maxw17=np.max(w17,1)
plt.contourf(x,z,maxw17,cmap=plt.get_cmap('plasma'))#, levels = np.linspace(0,9,9))
plt.ylabel('Aug 17',rotation=0,labelpad=30,fontweight='bold')
plt.colorbar()
plt.xticks([])
plt.ylim(0,20)
plt.subplot(3,2,4)
maxq17=np.max(q17,1)
maxq17[maxq17<0.001]=np.log(0)
plt.contourf(x,z,maxq17)#,levels = np.linspace(0,3.2,9))
plt.colorbar()
plt.xticks([])
plt.yticks([])
plt.ylim(0,20)
plt.subplot(3,2,5)
maxw23=np.max(w23,1)
plt.contourf(x,z,maxw23)#,levels = np.linspace(0,28,9))
plt.ylabel('Feb 23',rotation=0,labelpad=30,fontweight='bold')
plt.colorbar()
plt.ylim(0,20)
plt.subplot(3,2,6)
maxq23=np.max(q23,1)
maxq23[maxq23<0.001]=np.log(0)
plt.contourf(x,z,maxq23)#,levels = np.linspace(0,12,9))
plt.yticks([])
plt.ylim(0,20)
plt.colorbar()
fig.tight_layout()
plt.savefig('panel6.png')
plt.clf()

plt.contourf(x,z,maxq11)#,levels = np.linspace(0,24,9))
plt.title('Max Condensate')
plt.colorbar(label='g/kg')
#plt.xticks([])
#plt.yticks([])
plt.ylim(0,20)
plt.savefig('slicecond.png')



